import Series from "../series";
import { AxisPosition, D3Selection, Datum, EventBus, FlagRendererAccessors, RendererAccessor, RendererClass, RendererOptions, RendererType, State } from "../../typings";
export declare type Options = RendererOptions<FlagRendererAccessors>;
declare class Flag implements RendererClass<FlagRendererAccessors> {
    data: Datum[];
    el: D3Selection;
    events: EventBus;
    options: Options;
    position: "x" | "y";
    scale: any;
    series: Series;
    state: State;
    type: RendererType;
    color: RendererAccessor<string>;
    description: RendererAccessor<string>;
    direction: RendererAccessor<"up" | "down">;
    label: RendererAccessor<string>;
    x: RendererAccessor<number | Date | string>;
    y: RendererAccessor<number | Date | string>;
    axis: AxisPosition;
    axisOffset: number;
    axisPadding: number;
    flagHeight: number;
    flagWidth: number;
    constructor(state: State, events: EventBus, el: D3Selection, data: Datum[], options: Options, series: Series);
    update(data: Datum[], options: Options): void;
    draw(): void;
    close(): void;
    dataForAxis(axis: "x" | "y"): any[];
    private validate(d);
    private appendSeriesGroup(el);
    private setAxisScales();
    private assignAccessors(customAccessors);
    private assignConfig(customConfig);
    private getAttributes();
    private positionLabel(attributes);
    private flagPath(attributes);
    private hoverFlagPath(attributes);
    private onFlagHover(attributes);
    private onFlagLeave(d, el);
}
export default Flag;
