import * as general1 from "./general-1"
import * as general2 from "./general-2"
import * as general3 from "./general-3"
import * as axes1 from "./axes-1"
import * as axes2 from "./axes-2"
import * as axes3 from "./axes-3"
import * as axes4 from "./axes-4"
import * as axes5 from "./axes-5"
import * as area1 from "./area-1"
import * as area2 from "./area-2"
import * as area3 from "./area-3"
import * as area4 from "./area-4"
import * as bars1 from "./bars-1"
import * as bars2 from "./bars-2"
import * as bars3 from "./bars-3"
import * as bars4 from "./bars-4"
import * as flag1 from "./flag-1"
import * as symbol1 from "./symbol-1"
import * as symbol2 from "./symbol-2"
import * as range1 from "./range-1"

export default [general1, general2, general3, axes1, axes2, axes3, axes4, axes5, area1, area2, area3, area4, bars1, bars2, bars3, bars4, flag1]
