// flow-typed signature: 5f59d345ddfff83b317acb6b20ab459a
// flow-typed version: <<STUB>>/rollup-plugin-jsx_v^1.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-jsx/index' {
  declare module.exports: $Exports<'rollup-plugin-jsx'>;
}
declare module 'rollup-plugin-jsx/index.js' {
  declare module.exports: $Exports<'rollup-plugin-jsx'>;
}
