import "d3-transition";
import { EventBus, FocusElement, NodeSelection, ProcessFlowConfig, Renderer, SeriesEl, State, TNode } from "../typings";
declare class Nodes implements Renderer {
    config: ProcessFlowConfig;
    data: TNode[];
    el: SeriesEl;
    events: EventBus;
    state: State;
    constructor(state: State, events: EventBus, el: SeriesEl);
    private onMouseOver(d, element);
    private mouseOver(element, d, hideLabel?);
    focusElement(focusElement: FocusElement): void;
    highlight(element: NodeSelection, d: TNode, keepCurrent?: boolean): void;
    private removeHighlights();
    private focusPoint(element, d);
    private onMouseOut();
    draw(data: TNode[]): void;
    private borderScale(scale);
    private translate(d);
    private rotate(d);
    private enterAndUpdate(groups);
    private getNodeBoundingRect(el);
    private getLabelPosition(d);
    private getAutomaticLabelPosition(d);
    private getNodeLabelX(d, el);
    private getNodeLabelY(d, el);
    private getLabelText(d);
    private updateNodeLabels();
}
export default Nodes;
