// flow-typed signature: cd98bca372afde087c864b047de0b3c1
// flow-typed version: <<STUB>>/jest-glamor-react_v^3.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-glamor-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-glamor-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-glamor-react/dist/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-glamor-react/dist/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-glamor-react/dist/replace-class-names.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/replace-class-names'>;
}
declare module 'jest-glamor-react/dist/serializer.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/serializer'>;
}
declare module 'jest-glamor-react/index' {
  declare module.exports: $Exports<'jest-glamor-react'>;
}
declare module 'jest-glamor-react/index.js' {
  declare module.exports: $Exports<'jest-glamor-react'>;
}
