import { D3Selection, EventBus, State, StateWriter } from "./typings";
import "d3-transition";
declare class Renderer {
    private angleScale;
    private arc;
    private currentTranslation;
    private data;
    private dataHandler;
    private el;
    private events;
    private mouseOverDatum;
    private previous;
    private radiusScale;
    private radius;
    private state;
    private stateWriter;
    private topNode;
    private total;
    private zoomNode;
    constructor(state: State, stateWriter: StateWriter, events: EventBus, el: D3Selection);
    draw(): void;
    private exit(arcs, duration, disableAnimations);
    private arcClass(d);
    private enterAndUpdate(arcs, duration, disableAnimations);
    private compute();
    private endAngle(d);
    private translate();
    private translateBack(point);
    private isEqual(d1);
    private isSibling(d1);
    private findSiblings(data, d);
    private findAncestor(data, d);
    private findDatum(data, d);
    private arcTween(d);
    private removeArcTween(d);
    private onClick(payload);
    private zoomOut(payload);
    private onMouseOver(d, el);
    private highlightPath(d, el);
    private onMouseLeave(d, el);
    private removeTruncationArrows();
    private arrowTransformation(d);
    private updateTruncationArrows();
}
export default Renderer;
