import "d3-transition";
import { ComputedData, D3Selection, Datum, EventBus, LegendDatum, Object, Partial, Renderer, RendererAccessor, State } from "../typings";
declare class Gauge implements Renderer {
    color: RendererAccessor<string>;
    comparison: Datum;
    computed: ComputedData;
    currentTranslation: [number, number];
    data: Datum[];
    drawn: boolean;
    el: D3Selection;
    events: EventBus;
    extent: string;
    key: RendererAccessor<string>;
    previous: Partial<ComputedData>;
    state: State;
    target: number;
    total: number;
    type: "donut" | "polar" | "gauge";
    value: RendererAccessor<number>;
    constructor(state: State, events: EventBus, el: D3Selection, options: Object<any>);
    updateOptions(options: Object<any>): void;
    setData(data: Datum[]): void;
    draw(): void;
    private initialDraw();
    private updateDraw();
    private arcAttributes();
    private arcColor(d);
    private angleRange();
    private totalYOffset();
    private arcTween(d, i);
    private lineTween(comparison);
    private centerDisplayString();
    private updateComparison();
    private compute();
    private angleValue(d);
    private fillGaugeExtent();
    private runningTotal();
    private computeArcs(computed);
    private computeOuter(drawingDims, margin);
    private computeInner(outerRadius);
    private onMouseOver(d);
    private updateElementHover(datapoint);
    private highlightElement(key);
    private onMouseOut();
    dataForLegend(): LegendDatum[];
    remove(): void;
}
export default Gauge;
