import "d3-transition";
import { ComputedArcs, ComputedData, ComputedDatum, ComputedInitial, D3Selection, Datum, EventBus, HoverPayload, LegendDatum, Object, Partial, Renderer, RendererAccessor, State } from "../typings";
declare class Gauge implements Renderer {
    color: RendererAccessor<string>;
    comparison: Datum;
    computed: ComputedData;
    currentTranslation: [number, number];
    data: Datum[];
    drawn: boolean;
    el: D3Selection;
    events: EventBus;
    extent: string;
    key: RendererAccessor<string>;
    previous: Partial<ComputedData>;
    state: State;
    target: number;
    total: number;
    type: "donut" | "polar" | "gauge";
    value: RendererAccessor<number>;
    constructor(state: State, events: EventBus, el: D3Selection, options: Object<any>);
    updateOptions(options: Object<any>): void;
    setData(data: Datum[]): void;
    draw(): void;
    initialDraw(): void;
    updateDraw(): void;
    arcAttributes(): Object<any>;
    angleRange(): [number, number];
    totalYOffset(): string;
    arcTween(d: ComputedDatum, i: number): (t: number) => string;
    lineTween(comparison: Object<any>): (t: number) => string;
    centerDisplayString(): string;
    updateComparison(): void;
    compute(): void;
    angleValue(d: Datum): number;
    fillGaugeExtent(): void;
    runningTotal(): number[];
    computeArcs(computed: ComputedInitial): ComputedArcs;
    computeOuter(drawingDims: {
        width: number;
        height: number;
    }, margin: number): number;
    computeInner(outerRadius: any): number;
    onMouseOver(d: ComputedDatum): void;
    updateElementHover(datapoint: HoverPayload): void;
    highlightElement(key: string): void;
    onMouseOut(): void;
    dataForLegend(): LegendDatum[];
    remove(): void;
}
export default Gauge;
