import "d3-transition";
import { D3Selection, Datum, EventBus, LegendDatum, Object, Renderer, RendererAccessor, State } from "../typings";
declare class Gauge implements Renderer {
    private color;
    private comparison;
    private computed;
    private currentTranslation;
    private data;
    private drawn;
    private el;
    private events;
    private extent;
    private previousComputed;
    private target;
    private total;
    key: RendererAccessor<string>;
    state: State;
    type: "donut" | "polar" | "gauge";
    value: RendererAccessor<number>;
    constructor(state: State, events: EventBus, el: D3Selection, options: Object<any>);
    updateOptions(options: Object<any>): void;
    setData(data: Datum[]): void;
    draw(): void;
    private initialDraw();
    private updateDraw();
    private arcAttributes();
    private arcColor(d);
    private angleRange();
    private totalYOffset();
    private arcTween(d, i);
    private lineTween(comparison);
    private centerDisplayString();
    private updateComparison();
    private compute();
    private angleValue(d);
    private fillGaugeExtent();
    private runningTotal();
    private computeArcs(computed);
    private computeOuterRadius(drawingDims, margin);
    private computeInnerRadius(outerRadius);
    private onMouseOver(d);
    private updateElementHover(datapoint);
    private highlightElement(key);
    private onMouseOut();
    dataForLegend(): LegendDatum[];
    remove(): void;
}
export default Gauge;
