import "d3-transition";
import { ComputedArcs, ComputedData, ComputedDatum, D3Selection, Datum, EventBus, HoverPayload, LegendDatum, Object, Partial, Renderer, RendererAccessor, State } from "../typings";
declare class Polar implements Renderer {
    color: RendererAccessor<string>;
    computed: ComputedData;
    currentTranslation: [number, number];
    data: Datum[];
    drawn: boolean;
    el: D3Selection;
    events: EventBus;
    key: RendererAccessor<string>;
    minSegmentWidth: number;
    previous: Partial<ComputedData>;
    state: State;
    type: "donut" | "polar" | "gauge";
    value: RendererAccessor<number>;
    constructor(state: State, events: EventBus, el: D3Selection, options: Object<any>);
    updateOptions(options: Object<any>): void;
    setData(data: Datum[]): void;
    draw(): void;
    initialDraw(): void;
    updateDraw(): void;
    arcAttributes(): Object<any>;
    fitToCanvas(): void;
    arcTween(d: ComputedDatum, i: number): (t: number) => string;
    removeArcTween(d: ComputedDatum, i: number): (t: number) => string;
    centerDisplayString(): string;
    compute(): void;
    angleValue(): number;
    computeArcs(computed: Partial<ComputedData>): ComputedArcs;
    computeOuter(drawingDims: {
        width: number;
        height: number;
    }, scaleFactor?: number): (d: Datum) => number;
    computeInner(data: ComputedDatum[], outerRadius: (d: Datum) => number): number;
    hoverOuter(radius: any): any;
    onMouseOver(d: ComputedDatum): void;
    updateElementHover(datapoint: HoverPayload): void;
    highlightElement(key: string): void;
    onMouseOut(): void;
    dataForLegend(): LegendDatum[];
    remove(): void;
}
export default Polar;
