import * as general1 from "./general-1"
import * as general2 from "./general-2"
import * as general3 from "./general-3"
import * as donut1 from "./donut-1"
import * as donut2 from "./donut-2"
import * as gauge1 from "./gauge-1"
import * as gauge2 from "./gauge-2"
import * as gauge3 from "./gauge-3"
import * as gauge4 from "./gauge-4"
import * as gauge5 from "./gauge-5"
import * as gauge6 from "./gauge-6"
import * as gauge7 from "./gauge-7"
import * as polar1 from "./polar-1"
import * as polar2 from "./polar-2"

export default [general1, general2, general3, donut1, donut2, gauge1, gauge2, gauge3, gauge4, gauge5, gauge6, gauge7]
