// flow-typed signature: 0b154228cb746f2aa78dafc55d42ea97
// flow-typed version: <<STUB>>/component-playground_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'component-playground'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'component-playground' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'component-playground/demo/app' {
  declare module.exports: any;
}

declare module 'component-playground/demo/components/button' {
  declare module.exports: any;
}

declare module 'component-playground/demo/components/debug-info' {
  declare module.exports: any;
}

declare module 'component-playground/demo/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'component-playground/demo/webpack.config.hot' {
  declare module.exports: any;
}

declare module 'component-playground/dist/component-playground' {
  declare module.exports: any;
}

declare module 'component-playground/dist/component-playground.min' {
  declare module.exports: any;
}

declare module 'component-playground/karma.conf.coverage' {
  declare module.exports: any;
}

declare module 'component-playground/karma.conf.dev' {
  declare module.exports: any;
}

declare module 'component-playground/karma.conf' {
  declare module.exports: any;
}

declare module 'component-playground/lib/components/doc' {
  declare module.exports: any;
}

declare module 'component-playground/lib/components/editor' {
  declare module.exports: any;
}

declare module 'component-playground/lib/components/es6-preview' {
  declare module.exports: any;
}

declare module 'component-playground/lib/components/playground' {
  declare module.exports: any;
}

declare module 'component-playground/lib/components/preview' {
  declare module.exports: any;
}

declare module 'component-playground/lib/index' {
  declare module.exports: any;
}

declare module 'component-playground/src/components/doc' {
  declare module.exports: any;
}

declare module 'component-playground/src/components/editor' {
  declare module.exports: any;
}

declare module 'component-playground/src/components/es6-preview' {
  declare module.exports: any;
}

declare module 'component-playground/src/components/playground' {
  declare module.exports: any;
}

declare module 'component-playground/src/components/preview' {
  declare module.exports: any;
}

declare module 'component-playground/src/index' {
  declare module.exports: any;
}

declare module 'component-playground/test/client/main' {
  declare module.exports: any;
}

declare module 'component-playground/test/client/specs/playground.spec' {
  declare module.exports: any;
}

declare module 'component-playground/webpack.config.coverage' {
  declare module.exports: any;
}

declare module 'component-playground/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'component-playground/webpack.config' {
  declare module.exports: any;
}

declare module 'component-playground/webpack.config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'component-playground/demo/app.jsx' {
  declare module.exports: $Exports<'component-playground/demo/app'>;
}
declare module 'component-playground/demo/components/button.jsx' {
  declare module.exports: $Exports<'component-playground/demo/components/button'>;
}
declare module 'component-playground/demo/components/debug-info.jsx' {
  declare module.exports: $Exports<'component-playground/demo/components/debug-info'>;
}
declare module 'component-playground/demo/webpack.config.dev.js' {
  declare module.exports: $Exports<'component-playground/demo/webpack.config.dev'>;
}
declare module 'component-playground/demo/webpack.config.hot.js' {
  declare module.exports: $Exports<'component-playground/demo/webpack.config.hot'>;
}
declare module 'component-playground/dist/component-playground.js' {
  declare module.exports: $Exports<'component-playground/dist/component-playground'>;
}
declare module 'component-playground/dist/component-playground.min.js' {
  declare module.exports: $Exports<'component-playground/dist/component-playground.min'>;
}
declare module 'component-playground/karma.conf.coverage.js' {
  declare module.exports: $Exports<'component-playground/karma.conf.coverage'>;
}
declare module 'component-playground/karma.conf.dev.js' {
  declare module.exports: $Exports<'component-playground/karma.conf.dev'>;
}
declare module 'component-playground/karma.conf.js' {
  declare module.exports: $Exports<'component-playground/karma.conf'>;
}
declare module 'component-playground/lib/components/doc.js' {
  declare module.exports: $Exports<'component-playground/lib/components/doc'>;
}
declare module 'component-playground/lib/components/editor.js' {
  declare module.exports: $Exports<'component-playground/lib/components/editor'>;
}
declare module 'component-playground/lib/components/es6-preview.js' {
  declare module.exports: $Exports<'component-playground/lib/components/es6-preview'>;
}
declare module 'component-playground/lib/components/playground.js' {
  declare module.exports: $Exports<'component-playground/lib/components/playground'>;
}
declare module 'component-playground/lib/components/preview.js' {
  declare module.exports: $Exports<'component-playground/lib/components/preview'>;
}
declare module 'component-playground/lib/index.js' {
  declare module.exports: $Exports<'component-playground/lib/index'>;
}
declare module 'component-playground/src/components/doc.jsx' {
  declare module.exports: $Exports<'component-playground/src/components/doc'>;
}
declare module 'component-playground/src/components/editor.jsx' {
  declare module.exports: $Exports<'component-playground/src/components/editor'>;
}
declare module 'component-playground/src/components/es6-preview.jsx' {
  declare module.exports: $Exports<'component-playground/src/components/es6-preview'>;
}
declare module 'component-playground/src/components/playground.jsx' {
  declare module.exports: $Exports<'component-playground/src/components/playground'>;
}
declare module 'component-playground/src/components/preview.jsx' {
  declare module.exports: $Exports<'component-playground/src/components/preview'>;
}
declare module 'component-playground/src/index.js' {
  declare module.exports: $Exports<'component-playground/src/index'>;
}
declare module 'component-playground/test/client/main.js' {
  declare module.exports: $Exports<'component-playground/test/client/main'>;
}
declare module 'component-playground/test/client/specs/playground.spec.js' {
  declare module.exports: $Exports<'component-playground/test/client/specs/playground.spec'>;
}
declare module 'component-playground/webpack.config.coverage.js' {
  declare module.exports: $Exports<'component-playground/webpack.config.coverage'>;
}
declare module 'component-playground/webpack.config.dev.js' {
  declare module.exports: $Exports<'component-playground/webpack.config.dev'>;
}
declare module 'component-playground/webpack.config.js' {
  declare module.exports: $Exports<'component-playground/webpack.config'>;
}
declare module 'component-playground/webpack.config.test.js' {
  declare module.exports: $Exports<'component-playground/webpack.config.test'>;
}
