// flow-typed signature: 93e42eb54daa8599dd0a3fc914470497
// flow-typed version: <<STUB>>/contiamo-ui-utils_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contiamo-ui-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contiamo-ui-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contiamo-ui-utils/flow-typed/contiamo' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-plugin-external-helpers_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-config-fbjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-relay_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/glamor_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/jest-glamor-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/jest-serializer-enzyme_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-image_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/flow-typed/npm/tinycolor2_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/lib/utils' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/rollup.config' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/src/animations' {
  declare module.exports: any;
}

declare module 'contiamo-ui-utils/src/color' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contiamo-ui-utils/flow-typed/contiamo.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/contiamo'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-plugin-external-helpers_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-plugin-external-helpers_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-jest_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-preset-jest_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-config-fbjs_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-config-fbjs_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/eslint-plugin-relay_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/eslint-plugin-relay_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/glamor_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/glamor_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/jest-glamor-react_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/jest-glamor-react_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/jest-serializer-enzyme_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/jest-serializer-enzyme_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-commonjs_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-flow_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-image_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-image_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-jsx_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'contiamo-ui-utils/flow-typed/npm/tinycolor2_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/flow-typed/npm/tinycolor2_vx.x.x'>;
}
declare module 'contiamo-ui-utils/index' {
  declare module.exports: $Exports<'contiamo-ui-utils'>;
}
declare module 'contiamo-ui-utils/index.js' {
  declare module.exports: $Exports<'contiamo-ui-utils'>;
}
declare module 'contiamo-ui-utils/lib/utils.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/lib/utils'>;
}
declare module 'contiamo-ui-utils/rollup.config.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/rollup.config'>;
}
declare module 'contiamo-ui-utils/src/animations.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/src/animations'>;
}
declare module 'contiamo-ui-utils/src/color.js' {
  declare module.exports: $Exports<'contiamo-ui-utils/src/color'>;
}
