// flow-typed signature: 24f90086d42a650edb22520b9a3765e8
// flow-typed version: <<STUB>>/contiamo-ui-components_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contiamo-ui-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contiamo-ui-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contiamo-ui-components/flow-typed/App.theme.type' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/contiamo' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-config-fbjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-relay_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/glamor_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/glamorous_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/jest-glamor-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/jest-serializer-enzyme_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/react-icons_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/react-router-dom_v4.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-alias_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-image_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/flow-typed/npm/tinycolor2_vx.x.x' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/lib/components' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/rollup.config' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Button/__tests__/Button.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Button/Button' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Card/__tests__/Card.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Card/Card' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Chip/__tests__/Chip.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Chip/Chip' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/__tests__/Header.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Header' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Item/__tests__/HeaderItem.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Item/HeaderItem' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Separator/__tests__/HeaderSeparator.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Separator/HeaderSeparator' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Title/__tests__/HeaderTitle.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Header/Title/HeaderTitle' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Input/__tests__/Input.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Input/Input' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/PlusChip/__tests__/PlusChip.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/PlusChip/PlusChip' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/__mocks__/Select.mock' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/__tests__/Select.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/Filter/SelectFilter' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/Option/SelectOption' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/Select' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Select/Select.style' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/__tests__/Sidebar.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Item/__tests__/SidebarItem.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Item/SidebarItem' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Item/SidebarItem.style' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Link/__tests__/SidebarLink.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Link/SidebarLink' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Sidebar/Sidebar' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/__tests__/SideNavigation.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Header/__tests__/SideNavigationHeader.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Header/SideNavigationHeader' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Item/__tests__/SideNavigationItem.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Item/SideNavigationItem' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Link/__tests__/SideNavigationLink.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/Link/SideNavigationLink' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/SideNavigation/SideNavigation' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Stat/__tests__/Stat.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Stat/Stat' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/theme' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Tooltip/__tests__/Tooltip.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Tooltip/__tests__/withTooltip.test' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Tooltip/Tooltip.style' {
  declare module.exports: any;
}

declare module 'contiamo-ui-components/src/Tooltip/withTooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contiamo-ui-components/flow-typed/App.theme.type.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/App.theme.type'>;
}
declare module 'contiamo-ui-components/flow-typed/contiamo.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/contiamo'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-jest_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-jest_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-config-fbjs_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-config-fbjs_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/eslint-plugin-relay_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/eslint-plugin-relay_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/glamor_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/glamor_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/glamorous_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/glamorous_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/jest-glamor-react_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/jest-glamor-react_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/jest-serializer-enzyme_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/jest-serializer-enzyme_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/react-icons_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/react-icons_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/react-router-dom_v4.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/react-router-dom_v4.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-alias_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-alias_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-flow_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-image_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-image_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-jsx_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'contiamo-ui-components/flow-typed/npm/tinycolor2_vx.x.x.js' {
  declare module.exports: $Exports<'contiamo-ui-components/flow-typed/npm/tinycolor2_vx.x.x'>;
}
declare module 'contiamo-ui-components/index' {
  declare module.exports: $Exports<'contiamo-ui-components'>;
}
declare module 'contiamo-ui-components/index.js' {
  declare module.exports: $Exports<'contiamo-ui-components'>;
}
declare module 'contiamo-ui-components/lib/components.js' {
  declare module.exports: $Exports<'contiamo-ui-components/lib/components'>;
}
declare module 'contiamo-ui-components/rollup.config.js' {
  declare module.exports: $Exports<'contiamo-ui-components/rollup.config'>;
}
declare module 'contiamo-ui-components/src/Button/__tests__/Button.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Button/__tests__/Button.test'>;
}
declare module 'contiamo-ui-components/src/Button/Button.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Button/Button'>;
}
declare module 'contiamo-ui-components/src/Card/__tests__/Card.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Card/__tests__/Card.test'>;
}
declare module 'contiamo-ui-components/src/Card/Card.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Card/Card'>;
}
declare module 'contiamo-ui-components/src/Chip/__tests__/Chip.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Chip/__tests__/Chip.test'>;
}
declare module 'contiamo-ui-components/src/Chip/Chip.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Chip/Chip'>;
}
declare module 'contiamo-ui-components/src/Header/__tests__/Header.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/__tests__/Header.test'>;
}
declare module 'contiamo-ui-components/src/Header/Header.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Header'>;
}
declare module 'contiamo-ui-components/src/Header/Item/__tests__/HeaderItem.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Item/__tests__/HeaderItem.test'>;
}
declare module 'contiamo-ui-components/src/Header/Item/HeaderItem.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Item/HeaderItem'>;
}
declare module 'contiamo-ui-components/src/Header/Separator/__tests__/HeaderSeparator.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Separator/__tests__/HeaderSeparator.test'>;
}
declare module 'contiamo-ui-components/src/Header/Separator/HeaderSeparator.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Separator/HeaderSeparator'>;
}
declare module 'contiamo-ui-components/src/Header/Title/__tests__/HeaderTitle.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Title/__tests__/HeaderTitle.test'>;
}
declare module 'contiamo-ui-components/src/Header/Title/HeaderTitle.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Header/Title/HeaderTitle'>;
}
declare module 'contiamo-ui-components/src/Input/__tests__/Input.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Input/__tests__/Input.test'>;
}
declare module 'contiamo-ui-components/src/Input/Input.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Input/Input'>;
}
declare module 'contiamo-ui-components/src/PlusChip/__tests__/PlusChip.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/PlusChip/__tests__/PlusChip.test'>;
}
declare module 'contiamo-ui-components/src/PlusChip/PlusChip.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/PlusChip/PlusChip'>;
}
declare module 'contiamo-ui-components/src/Select/__mocks__/Select.mock.js' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/__mocks__/Select.mock'>;
}
declare module 'contiamo-ui-components/src/Select/__tests__/Select.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/__tests__/Select.test'>;
}
declare module 'contiamo-ui-components/src/Select/Filter/SelectFilter.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/Filter/SelectFilter'>;
}
declare module 'contiamo-ui-components/src/Select/Option/SelectOption.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/Option/SelectOption'>;
}
declare module 'contiamo-ui-components/src/Select/Select.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/Select'>;
}
declare module 'contiamo-ui-components/src/Select/Select.style.js' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Select/Select.style'>;
}
declare module 'contiamo-ui-components/src/Sidebar/__tests__/Sidebar.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/__tests__/Sidebar.test'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Item/__tests__/SidebarItem.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Item/__tests__/SidebarItem.test'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Item/SidebarItem.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Item/SidebarItem'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Item/SidebarItem.style.js' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Item/SidebarItem.style'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Link/__tests__/SidebarLink.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Link/__tests__/SidebarLink.test'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Link/SidebarLink.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Link/SidebarLink'>;
}
declare module 'contiamo-ui-components/src/Sidebar/Sidebar.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Sidebar/Sidebar'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/__tests__/SideNavigation.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/__tests__/SideNavigation.test'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Header/__tests__/SideNavigationHeader.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Header/__tests__/SideNavigationHeader.test'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Header/SideNavigationHeader.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Header/SideNavigationHeader'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Item/__tests__/SideNavigationItem.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Item/__tests__/SideNavigationItem.test'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Item/SideNavigationItem.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Item/SideNavigationItem'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Link/__tests__/SideNavigationLink.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Link/__tests__/SideNavigationLink.test'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/Link/SideNavigationLink.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/Link/SideNavigationLink'>;
}
declare module 'contiamo-ui-components/src/SideNavigation/SideNavigation.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/SideNavigation/SideNavigation'>;
}
declare module 'contiamo-ui-components/src/Stat/__tests__/Stat.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Stat/__tests__/Stat.test'>;
}
declare module 'contiamo-ui-components/src/Stat/Stat.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Stat/Stat'>;
}
declare module 'contiamo-ui-components/src/theme.js' {
  declare module.exports: $Exports<'contiamo-ui-components/src/theme'>;
}
declare module 'contiamo-ui-components/src/Tooltip/__tests__/Tooltip.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Tooltip/__tests__/Tooltip.test'>;
}
declare module 'contiamo-ui-components/src/Tooltip/__tests__/withTooltip.test.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Tooltip/__tests__/withTooltip.test'>;
}
declare module 'contiamo-ui-components/src/Tooltip/Tooltip.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Tooltip/Tooltip'>;
}
declare module 'contiamo-ui-components/src/Tooltip/Tooltip.style.js' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Tooltip/Tooltip.style'>;
}
declare module 'contiamo-ui-components/src/Tooltip/withTooltip.jsx' {
  declare module.exports: $Exports<'contiamo-ui-components/src/Tooltip/withTooltip'>;
}
