export declare const chartContainer: string;
export declare const focusLegend: string;
export declare const legend: string;
export declare const legendTopBottom: string;
export declare const seriesLegend: string;
export declare const drawingContainer: string;
export declare const chartBackground: string;
export declare const rule: string;
export declare const componentFocus: string;
