import { AxisClass, AxisComputed, AxisPosition, AxisType, CategoricalAxisOptions, D3Selection, EventBus, State, StateWriter } from "../typings";
declare class CategoricalAxis implements AxisClass<string> {
    computed: AxisComputed;
    data: string[];
    el: D3Selection;
    events: EventBus;
    isXAxis: boolean;
    position: AxisPosition;
    previous: AxisComputed;
    state: State;
    stateWriter: StateWriter;
    type: AxisType;
    margin: number;
    minTicks: number;
    minTopOffsetTopTick: number;
    tickOffset: number;
    tickSpacing: number;
    outerPadding: number;
    sort: boolean;
    values: string[];
    constructor(state: State, stateWriter: StateWriter, events: EventBus, el: D3Selection, position: AxisPosition);
    validate(value: any): boolean;
    private updateOptions(options);
    update(options: CategoricalAxisOptions, data: string[]): void;
    compute(): void;
    private computeTickWidth();
    private computeBarPositions(defaultBarWidth, tickWidth);
    private computeRange(tickWidth);
    draw(): void;
    private drawTicks();
    private scaleWithOffset(computed);
    private getAttributes();
    private getStartAttributes(attributes);
    private adjustMargins();
    private drawBorder();
    close(): void;
}
export default CategoricalAxis;
