import { Canvas, D3Selection, EventBus, Object, SeriesEl, State, StateWriter } from "./typings";
declare class PieChartCanvas implements Canvas {
    drawingContainer: D3Selection;
    protected elements: Object<D3Selection>;
    chartContainer: D3Selection;
    el: SeriesEl;
    events: EventBus;
    protected state: State;
    protected elMap: Object<D3Selection>;
    stateWriter: StateWriter;
    constructor(state: State, stateWriter: StateWriter, events: EventBus, context: Element);
    private renderChartContainer(context);
    private onMouseEnter();
    private onMouseLeave();
    private onClick();
    private renderLegend();
    private renderDrawingContainer();
    private renderEl();
    private renderShadows();
    private prefixedId(id);
    private shadowDefinitionId();
    private renderDrawingGroup();
    private renderFocusElements();
    private renderFocusLabel();
    private renderComponentFocus();
    private drawingContainerDims();
    draw(): void;
    remove(): void;
    elementFor(component: string): D3Selection;
}
export default PieChartCanvas;
