module.exports = {
  exportPathMap: () => ({
    "/": { page: "/", query: { title: "Operational UI" } },
    "/getting-started": { page: "/getting-started", query: { title: "Getting Started" } },
    "/components": { page: "/components", query: { title: "Components" } },
    "/components/breadcrumbs": { page: "/components/breadcrumbs", query: { title: "Breadcrumbs" } },
    "/components/breakdowns": { page: "/components/breakdowns", query: { title: "Breakdowns" } },
    "/components/buttons": { page: "/components/buttons", query: { title: "Buttons" } },
    "/components/cards": { page: "/components/cards", query: { title: "Cards" } },
    "/components/chips": { page: "/components/chips", query: { title: "Chips" } },
    "/components/color-pickers": { page: "/components/color-pickers", query: { title: "Color Pickers" } },
    "/components/colors": { page: "/components/colors", query: { title: "Colors" } },
    "/components/context-menus": { page: "/components/context-menus", query: { title: "Context Menus" } },
    "/components/date-pickers": { page: "/components/date-pickers", query: { title: "Datepickers" } },
    "/components/form-fields": { page: "/components/form-fields", query: { title: "Form Fields" } },
    "/components/grids": { page: "/components/grids", query: { title: "Grids" } },
    "/components/icons": { page: "/components/icons", query: { title: "Icons" } },
    "/components/info-tiles": { page: "/components/info-tiles", query: { title: "Infotiles" } },
    "/components/messages": { page: "/components/messages", query: { title: "Messages" } },
    "/components/modals": { page: "/components/modals", query: { title: "Modals" } },
    "/components/paginators": { page: "/components/paginators", query: { title: "Paginators" } },
    "/components/records": { page: "/components/records", query: { title: "Records" } },
    "/components/sidebar": { page: "/components/sidebar", query: { title: "Sidebar" } },
    "/components/loaders": { page: "/components/loaders", query: { title: "Loaders" } },
    "/components/switches": { page: "/components/switches", query: { title: "Switches" } },
    "/components/tabs": { page: "/components/tabs", query: { title: "Tabs" } },
    "/components/tables": { page: "/components/tables", query: { title: "Tables" } },
    "/components/timeline": { page: "/components/timeline", query: { title: "Timeline" } },
    "/components/tooltips": { page: "/components/tooltips", query: { title: "Tooltips" } },
    "/components/typography": { page: "/components/typography", query: { title: "Typography" } },
    "/components/uploads": { page: "/components/uploads", query: { title: "Uploads" } },
    "/blocks": { page: "/blocks", query: { title: "Blocks" } },
    "/blocks/filters": { page: "/blocks/filters", query: { title: "Filters" } },
    "/blocks/auth": { page: "/blocks/auth", query: { title: "Auth" } },
    "/visualizations": { page: "/visualizations", query: { title: "Visualizations" } },
    "/visualizations/pie-chart": { page: "/visualizations/pie-chart", query: { title: "Pie Chart" } },
    "/visualizations/pie-chart/testcases": { page: "/visualizations/pie-chart/testcases", query: { title: "Test Cases" } },
    "/visualizations/pie-chart/donut_testcases": { page: "/visualizations/pie-chart/donut_testcases", query: { title: "Test Cases" } },
    "/visualizations/pie-chart/gauge_testcases": { page: "/visualizations/pie-chart/gauge_testcases", query: { title: "Test Cases" } },
    "/visualizations/pie-chart/polar_testcases": { page: "/visualizations/pie-chart/polar_testcases", query: { title: "Test Cases" } },
    "/visualizations/process-flow": { page: "/visualizations/process-flow", query: { title: "Process Flow" } },
    "/visualizations/process-flow/testcases": { page: "/visualizations/process-flow/testcases", query: { title: "Test Cases" } },
    "/documentation": { page: "/documentation", query: { title: "Documentation" } },
    "/documentation/design-guidelines": { page: "/documentation/design-guidelines", query: { title: "Design Guidelines" } },
    "/documentation/api": { page: "/documentation/api", query: { title: "API Design" } },
    "/documentation/theming": { page: "/documentation/theming", query: { title: "Theming" } }
  })
}
