module.exports = {
  exportPathMap: () => ({
    "/": { page: "/", query: { title: "Operational UI" } },
    "/components": { page: "/components", query: { title: "Components" } },
    "/components/breakdowns": { page: "/components/breakdowns", query: { title: "Breakdowns" } },
    "/components/buttons": { page: "/components/buttons", query: { title: "Buttons" } },
    "/components/cards": { page: "/components/cards", query: { title: "Cards" } },
    "/components/chips": { page: "/components/chips", query: { title: "Chips" } },
    "/components/color-pickers": { page: "/components/color-pickers", query: { title: "Color Pickers" } },
    "/components/colors": { page: "/components/colors", query: { title: "Colors" } },
    "/components/context-menus": { page: "/components/context-menus", query: { title: "Context Menus" } },
    "/components/date-pickers": { page: "/components/date-pickers", query: { title: "Datepickers" } },
    "/components/form-fields": { page: "/components/form-fields", query: { title: "Form Fields" } },
    "/components/grids": { page: "/components/grids", query: { title: "Grids" } },
    "/components/icons": { page: "/components/icons", query: { title: "Icons" } },
    "/components/info-tiles": { page: "/components/info-tiles", query: { title: "Infotiles" } },
    "/components/modals": { page: "/components/modals", query: { title: "Modals" } },
    "/components/paginators": { page: "/components/paginators", query: { title: "Paginators" } },
    "/components/progress": { page: "/components/progress", query: { title: "Progress" } },
    "/components/sidebar": { page: "/components/sidebar", query: { title: "Sidebar" } },
    "/components/spinners": { page: "/components/spinners", query: { title: "Spinners" } },
    "/components/switches": { page: "/components/switches", query: { title: "Switches" } },
    "/components/tabs": { page: "/components/tabs", query: { title: "Tabs" } },
    "/components/timeline": { page: "/components/timeline", query: { title: "Timeline" } },
    "/components/tooltips": { page: "/components/tooltips", query: { title: "Tooltips" } },
    "/components/typography": { page: "/components/typography", query: { title: "Typography" } },
    "/components/uploads": { page: "/components/uploads", query: { title: "Uploads" } },
    "/blocks": { page: "/blocks", query: { title: "Blocks" } },
    "/blocks/filters": { page: "/blocks/filters", query: { title: "Filters" } },
    "/visualizations": { page: "/visualizations", query: { title: "Visualizations" } },
    "/visualizations/process-flow": { page: "/visualizations/process-flow", query: { title: "Process Flow" } },
    "/documentation": { page: "/documentation", query: { title: "Documentation" } },
    "/documentation/design-guidelines": { page: "/documentation/design-guidelines", query: { title: "Design Guidelines" } },
    "/documentation/api": { page: "/documentation/api", query: { title: "API Design" } },
    "/documentation/theming": { page: "/documentation/theming", query: { title: "Theming" } }
  })
}
